default: &default
  host: redis
  port: 6379
  db: 1

  namespace: msd_api
  count_namespace: count
  color_namespace: color
  recent_namespace: recent

development:
  <<: *default

production:
  <<: *default

test:
  <<: *default